services:
  postgresdb:
    container_name: postgres-container
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: securedoc.app
      POSTGRES_PASSWORD: root
      POSTGRES_DB: securedoc-db
    ports:
      - 5430:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:9.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: securedoc.admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 7000:80
    volumes:
      - ./pgadmin-volume:/var/lib/pgadmin
