POSTGRESQL_USERNAME: securedoc.app
POSTGRESQL_PASSWORD: root
POSTGRESQL_HOST: 127.0.0.1
POSTGRESQL_PORT: 5430
POSTGRESQL_DATABASE: securedoc-db

CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

EMAIL_HOST: smpt.gmail.com
EMAIL_PORT: 587
EMAIL_ID: stub
EMAIL_PASSWORD: stub
VERIFY_EMAIL_HOST: http://localhost:8085